
variable "aws_access_key" {
  type    = string
  default = "AKIA5EMJQ6ZF7GWRQVWH" #CAUTION: This is for demo purposes. DO NOT check in  your AWS crdentials in the git repo
}

variable "aws_secret_key" {
  type    = string
  default = "h8HQHVU/ZVaw00edEhH5TSMzFJyc4r2vyrQrXpjc"
}

variable "aws_subnet_id" {
  type    = string
  default = "subnet-0c729cd36e675fd81"
}

data "amazon-ami" "autogenerated_1" {
  access_key = "${var.aws_access_key}"
  filters = {
    name                = "amzn2-ami-hvm-2.0.*-gp2"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["amazon"]
  region      = "us-east-1"
  secret_key  = "${var.aws_secret_key}"
}

source "amazon-ebs" "autogenerated_1" {
  access_key            = "${var.aws_access_key}"
  ami_description       = "Landing page for book application"
  ami_name              = "booksite-amalin2"
  force_delete_snapshot = true
  force_deregister      = true
  instance_type         = "t3.micro"
  region                = "us-east-1"
  secret_key            = "${var.aws_secret_key}"
  security_group_filter {
    filters = {
      "tag:Class" = "packer"
    }
  }
  source_ami   = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username = "ec2-user"
  subnet_id    = "${var.aws_subnet_id}"
  tags = {
    Builder = "Packer"
    Role    = "Web"
    Team    = "Frontend"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = ["sudo mkdir -p /var/www/html", "sudo chown ec2-user:ec2-user /var/www/html"]
  }

  provisioner "file" {
    destination = "/var/www/html/"
    source      = "website/"
  }

  provisioner "shell" {
    script = "deploy.sh"
  }

}
